# -*- coding: utf-8 -*-
"""teste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16La3cFj4JpB_HtxaFFdwxVLtyM3agUbs
"""

import requests
from bs4 import BeautifulSoup
import csv
from datetime import datetime

def get_apartment_details(url):
    """ Extrai os detalhes de um imóvel a partir da URL """
    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers)

        if response.status_code != 200:
            print(f"Erro ao acessar {url} - Código {response.status_code}")
            return None

        soup = BeautifulSoup(response.text, 'html.parser')

        # Extração de dados
        title = soup.find('h1').text.strip() if soup.find('h1') else "N/A"
        price = soup.find('span', class_='price').text.strip() if soup.find('span', class_='price') else "N/A"
        address = soup.find('span', class_='address').text.strip() if soup.find('span', class_='address') else "N/A"

        # Características do imóvel
        characteristics = soup.find_all('li', class_='icon-feature')
        area = rooms = bathrooms = garages = "N/A"

        for char in characteristics:
            text = char.text.strip()
            if "m²" in text:
                area = text
            elif "quarto" in text:
                rooms = text
            elif "banheiro" in text:
                bathrooms = text
            elif "vaga" in text:
                garages = text

        return [url, title, price, address, area, rooms, bathrooms, garages]

    except Exception as e:
        print(f"Erro ao buscar detalhes do imóvel: {str(e)}")
        return None

def process_single_property():
    """ Processa apenas um imóvel e salva os dados em CSV """
    url = "https://www.imovelweb.com.br/propriedades/casa-para-aluguel-no-brooklin-paulista-3007053679.html"

    today = datetime.now().strftime('%Y-%m-%d')
    filename = f'preco_imovel_{today}.csv'

    with open(filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['URL', 'Título', 'Preço', 'Endereço', 'Área', 'Quartos', 'Banheiros', 'Vagas'])

        details = get_apartment_details(url)
        if details:
            writer.writerow(details)
            print(f"✅ Dados salvos em {filename}")
        else:
            print("❌ Erro ao obter os dados do imóvel.")

if __name__ == "__main__":
    process_single_property()